// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NavySeal.API.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NavySeal.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260616164656_AddDailyContest")]
    partial class AddDailyContest
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NavySeal.API.Models.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SeaLionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SeaLionId");

                    b.HasIndex("UserId");

                    b.HasIndex("SeaLionId", "CreatedAt");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("NavySeal.API.Models.ContestVote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ContestId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SeaLionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SeaLionId");

                    b.HasIndex("UserId");

                    b.HasIndex("ContestId", "UserId")
                        .IsUnique();

                    b.ToTable("ContestVotes");
                });

            modelBuilder.Entity("NavySeal.API.Models.DailyContest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("FinalizedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nomination")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("PeriodEndUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("PeriodStartUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("WinnerSeaLionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PeriodStartUtc")
                        .IsUnique();

                    b.HasIndex("WinnerSeaLionId");

                    b.HasIndex("FinalizedAt", "PeriodEndUtc");

                    b.ToTable("DailyContests");
                });

            modelBuilder.Entity("NavySeal.API.Models.Rating", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SeaLionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<byte>("Value")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("SeaLionId");

                    b.HasIndex("UserId", "SeaLionId")
                        .IsUnique();

                    b.ToTable("Ratings");
                });

            modelBuilder.Entity("NavySeal.API.Models.SeaLion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("UserId");

                    b.ToTable("SeaLions");
                });

            modelBuilder.Entity("NavySeal.API.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("NavySeal.API.Models.Comment", b =>
                {
                    b.HasOne("NavySeal.API.Models.SeaLion", "SeaLion")
                        .WithMany("Comments")
                        .HasForeignKey("SeaLionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NavySeal.API.Models.User", "User")
                        .WithMany("Comments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SeaLion");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NavySeal.API.Models.ContestVote", b =>
                {
                    b.HasOne("NavySeal.API.Models.DailyContest", "Contest")
                        .WithMany("Votes")
                        .HasForeignKey("ContestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NavySeal.API.Models.SeaLion", "SeaLion")
                        .WithMany("ContestVotes")
                        .HasForeignKey("SeaLionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NavySeal.API.Models.User", "User")
                        .WithMany("ContestVotes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contest");

                    b.Navigation("SeaLion");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NavySeal.API.Models.DailyContest", b =>
                {
                    b.HasOne("NavySeal.API.Models.SeaLion", "WinnerSeaLion")
                        .WithMany()
                        .HasForeignKey("WinnerSeaLionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("WinnerSeaLion");
                });

            modelBuilder.Entity("NavySeal.API.Models.Rating", b =>
                {
                    b.HasOne("NavySeal.API.Models.SeaLion", "SeaLion")
                        .WithMany("Ratings")
                        .HasForeignKey("SeaLionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NavySeal.API.Models.User", "User")
                        .WithMany("Ratings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SeaLion");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NavySeal.API.Models.SeaLion", b =>
                {
                    b.HasOne("NavySeal.API.Models.User", "User")
                        .WithMany("SeaLions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("NavySeal.API.Models.DailyContest", b =>
                {
                    b.Navigation("Votes");
                });

            modelBuilder.Entity("NavySeal.API.Models.SeaLion", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("ContestVotes");

                    b.Navigation("Ratings");
                });

            modelBuilder.Entity("NavySeal.API.Models.User", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("ContestVotes");

                    b.Navigation("Ratings");

                    b.Navigation("SeaLions");
                });
#pragma warning restore 612, 618
        }
    }
}
